### ISSUE TITLE
Add hardware acceleration support

### ISSUE THREAD

**Issue by Ilya87** [andrew-bibb/mbmp#9]
mbmp consumes about 25% CPU time (FullHD 60fps source, Intel Core i5-2500, Nvidia GTX 560). Other players consume less.

**Comment by andrew-bibb** [comment]
I meant to reply to this a couple of days ago, but I'm really backed up at the moment.  I did a bit of research into this and I'm pretty sure is it just a matter of promoting or demoting certain pipeline elements.  

Thank you for reporting it, and I will get to it.

**Comment by andrew-bibb** [comment]
I just uploaded a separate branch called issue09.  I've have an NVIDIA card and I am seeing some difference for mpeg files with and without the hardware decoder. Specifically my test video plays with hardware decoding enabled, but won't play without it.  I'm not sure that is exactly where we are supposed to be, but if you could download the branch and test I'd appreciate it.

There is still a lot of debug lines that will print if you start from the command line.  If it works I'll pull those out.  Biggest problem with this is finding documentation of all the different hardware decoders.  Using GStreamer I can find all decoders available, but I can't find a way to isolate only hardware decoders.  I had to hardcode a list of known decoders, but I don't think it is complete.   Another task before I can close this one out.
